name: Run Feedparser Script

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # or latest stable

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python main.py
