name: Run Logger Action Hourly

on:
  schedule:
    - cron: '0 * * * *'    # every hour
  workflow_dispatch:       # manual trigger
  push:
    branches:
      - main
    paths:
      - 'main.py'
      - 'action.yml'

jobs:
  log-via-action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Python Logger
        uses: ./
